spring.profiles.active=dev
spring.application.name=clyvo-api
#server.port=8081
spring.cache.cache-names=usuarios,tutores,pets
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html