# URL de conexão para o banco H2 em memória
spring.datasource.url=jdbc:h2:mem:clyvodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto correto para o Hibernate traduzir as queries para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Estratégia de geração do banco: 'update' cria/ajusta as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Exibe as queries SQL no console (Essencial para o professor ver a persistência acontecendo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilita o console web do H2 para inspecionar as tabelas pelo navegador se necessário
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true