# Define o perfil ativo.
spring.profiles.active=dev

# Configurações globais
spring.application.name=clyvo-api
server.port=8080

# Configuração do Cache Nativo do Spring
spring.cache.cache-names=usuarios,tutores,pets

# Configuração do Swagger / OpenAPI Path
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html